### ISSUE TITLE
Error: unable to verify the first certificate

### ISSUE THREAD

**Issue by shasti86** [harbur/kubernetic#23]
```Error: unable to verify the first certificate
    at TLSSocket.<anonymous> (_tls_wrap.js:1085:38)
    at emitNone (events.js:86:13)
    at TLSSocket.emit (events.js:185:7)
    at TLSSocket._finishInit (_tls_wrap.js:603:8)
    at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:433:38)
```
My kubectl works just fine. I have set skip TLS as true in my config and using token based authentication. 
Please advice.

**Comment by spiddy** [comment]
Authentication has been redone on v0.8.0, can you update and see if the error still persists?

**Comment by spiddy** [comment]
Related to #14 
flag `insecure-skip-tls-verify` is now supported since [v2.0.7](https://github.com/harbur/kubernetic/blob/master/CHANGELOG.md#v207)
