### ISSUE TITLE
Error updating popup on Ubuntu 20.04

### ISSUE THREAD

**Issue by AntonBlomstrom** [harbur/kubernetic#257]
Kubernetic's version 2.13.0

![image](https://user-images.githubusercontent.com/39986991/96445912-f094ea80-1210-11eb-9489-f61219e9d102.png)
I also get this log after clicking "OK":

```
Checking for update
(electron) 'getName function' is deprecated and will be removed. Please use 'name property' instead.
Error: Error: ENOENT: no such file or directory, open '/home/ab/Downloads/Kubernetic/resources/app-update.yml'
(node:44406) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, open '/home/ab/Downloads/Kubernetic/resources/app-update.yml'
(node:44406) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, open '/home/ab/Downloads/Kubernetic/resources/app-update.yml'
(node:44406) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:44406) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:44406) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:44406) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
[13:44:02.987] [info] /home/ab/.config/Kubernetic
[13:44:03.028] [info] URL is file:///home/ab/Downloads/Kubernetic/resources/app.asar/node_modules/@harbur/kubernetic-frontend/build/index.html?port=45424&token=ctbnf47rzvmksjhjr3ej9f&baseURL=/home/ab/Downloads/Kubernetic/resources/app.asar/public
[13:44:03.039] [info] starting up in "production" mode
cannot load config file: Config File "config" Not Found in "[/home/ab/config /etc/kubernetic-backend]"
[GIN-debug] [WARNING] Running in "debug" mode. Switch to "release" mode in production.
 - using env:   export GIN_MODE=release
 - using code:  gin.SetMode(gin.ReleaseMode)

[GIN-debug] GET    /healthz                  --> github.com/harbur/kubernetic-backend/pkg/apis.Healthz (3 handlers)
[GIN-debug] GET    /swagger/*any             --> github.com/swaggo/gin-swagger.CustomWrapHandler.func1 (3 handlers)
[GIN-debug] GET    /                         --> github.com/harbur/kubernetic-backend/pkg/routers.SetupRouter.func7 (3 handlers)
[GIN-debug] GET    /api/healthz              --> github.com/harbur/kubernetic-backend/pkg/apis.Healthz (5 handlers)
[GIN-debug] GET    /api/dashboard            --> github.com/harbur/kubernetic-backend/pkg/apis.GetDashboard (5 handlers)
[GIN-debug] GET    /api/charts               --> github.com/harbur/kubernetic-backend/pkg/apis.ListCharts (5 handlers)
[GIN-debug] GET    /api/charts/:repository/:name --> github.com/harbur/kubernetic-backend/pkg/apis.GetChart (5 handlers)
[GIN-debug] GET    /api/charts/:repository/:name/values --> github.com/harbur/kubernetic-backend/pkg/apis.GetChartValues (5 handlers)
[GIN-debug] GET    /api/charts/:repository/:name/readme --> github.com/harbur/kubernetic-backend/pkg/apis.GetChartReadme (5 handlers)
[GIN-debug] GET    /api/charts/:repository/:name/versions --> github.com/harbur/kubernetic-backend/pkg/apis.ListChartVersions (5 handlers)
[GIN-debug] GET    /api/config               --> github.com/harbur/kubernetic-backend/pkg/apis.ReadKubeConfig (5 handlers)
[GIN-debug] GET    /api/login                --> github.com/harbur/kubernetic-backend/pkg/apis.Login (5 handlers)
[GIN-debug] POST   /api/namespaces/:namespace/configmaps --> github.com/harbur/kubernetic-backend/pkg/apis.CreateConfigMap (5 handlers)
[GIN-debug] POST   /api/namespaces/:namespace/daemonsets --> github.com/harbur/kubernetic-backend/pkg/apis.CreateDaemonSet (5 handlers)
[GIN-debug] POST   /api/namespaces/:namespace/daemonsets/:name/rollout/restart --> github.com/harbur/kubernetic-backend/pkg/apis.RestartDaemonSet (5 handlers)
[GIN-debug] POST   /api/namespaces/:namespace/deployments --> github.com/harbur/kubernetic-backend/pkg/apis.CreateDeployment (5 handlers)
[GIN-debug] POST   /api/namespaces/:namespace/deployments/:name/rollout/restart --> github.com/harbur/kubernetic-backend/pkg/apis.RestartDeployment (5 handlers)
[GIN-debug] PUT    /api/namespaces/:namespace/deployments/:name/updateversion --> github.com/harbur/kubernetic-backend/pkg/apis.UpdateVersion (5 handlers)
[GIN-debug] POST   /api/namespaces/:namespace/horizontalpodautoscalers --> github.com/harbur/kubernetic-backend/pkg/apis.CreateHorizontalPodAutoscaler (5 handlers)
[GIN-debug] POST   /api/namespaces/:namespace/ingresses --> github.com/harbur/kubernetic-backend/pkg/apis.CreateIngress (5 handlers)
[GIN-debug] POST   /api/namespaces/:namespace/jobs --> github.com/harbur/kubernetic-backend/pkg/apis.CreateJob (5 handlers)
[GIN-debug] POST   /api/namespaces/:namespace/limitranges --> github.com/harbur/kubernetic-backend/pkg/apis.CreateLimitRange (5 handlers)
[GIN-debug] POST   /api/namespaces/:namespace/persistentvolumeclaims --> github.com/harbur/kubernetic-backend/pkg/apis.CreatePersistentVolumeClaim (5 handlers)
[GIN-debug] POST   /api/namespaces/:namespace/pods --> github.com/harbur/kubernetic-backend/pkg/apis.CreatePod (5 handlers)
[GIN-debug] POST   /api/namespaces/:namespace/releases --> github.com/harbur/kubernetic-backend/pkg/apis.CreateRelease (5 handlers)
[GIN-debug] GET    /api/namespaces/:namespace/releases --> github.com/harbur/kubernetic-backend/pkg/apis.ListNamespacedReleases (5 handlers)
[GIN-debug] GET    /api/namespaces/:namespace/releases/:name --> github.com/harbur/kubernetic-backend/pkg/apis.GetRelease (5 handlers)
[GIN-debug] PUT    /api/namespaces/:namespace/releases/:name --> github.com/harbur/kubernetic-backend/pkg/apis.UpgradeRelease (5 handlers)
[GIN-debug] PUT    /api/namespaces/:namespace/releases/:name/revision/:revision --> github.com/harbur/kubernetic-backend/pkg/apis.RollbackRelease (5 handlers)
[GIN-debug] GET    /api/namespaces/:namespace/releases/:name/hooks --> github.com/harbur/kubernetic-backend/pkg/apis.GetReleaseHooks (5 handlers)
[GIN-debug] GET    /api/namespaces/:namespace/releases/:name/manifest --> github.com/harbur/kubernetic-backend/pkg/apis.GetReleaseManifest (5 handlers)
[GIN-debug] GET    /api/namespaces/:namespace/releases/:name/manifestjson --> github.com/harbur/kubernetic-backend/pkg/apis.GetReleaseManifestJSON (5 handlers)
[GIN-debug] GET    /api/namespaces/:namespace/releases/:name/notes --> github.com/harbur/kubernetic-backend/pkg/apis.GetReleaseNotes (5 handlers)
[GIN-debug] GET    /api/namespaces/:namespace/releases/:name/values --> github.com/harbur/kubernetic-backend/pkg/apis.GetReleaseValues (5 handlers)
[GIN-debug] GET    /api/namespaces/:namespace/releases/:name/history --> github.com/harbur/kubernetic-backend/pkg/apis.GetReleaseHistory (5 handlers)
[GIN-debug] DELETE /api/namespaces/:namespace/releases/:name --> github.com/harbur/kubernetic-backend/pkg/apis.DeleteRelease (5 handlers)
[GIN-debug] GET    /api/releases             --> github.com/harbur/kubernetic-backend/pkg/apis.ListReleases (5 handlers)
[GIN-debug] POST   /api/namespaces/:namespace/replicasets --> github.com/harbur/kubernetic-backend/pkg/apis.CreateReplicaSet (5 handlers)
[GIN-debug] POST   /api/namespaces/:namespace/replicationcontrollers --> github.com/harbur/kubernetic-backend/pkg/apis.CreateReplicationController (5 handlers)
[GIN-debug] POST   /api/namespaces/:namespace/resourcequotas --> github.com/harbur/kubernetic-backend/pkg/apis.CreateResourceQuota (5 handlers)
[GIN-debug] POST   /api/namespaces/:namespace/secrets --> github.com/harbur/kubernetic-backend/pkg/apis.CreateSecret (5 handlers)
[GIN-debug] POST   /api/namespaces/:namespace/serviceaccounts --> github.com/harbur/kubernetic-backend/pkg/apis.CreateServiceAccount (5 handlers)
[GIN-debug] POST   /api/namespaces/:namespace/services --> github.com/harbur/kubernetic-backend/pkg/apis.CreateService (5 handlers)
[GIN-debug] POST   /api/namespaces/:namespace/statefulsets --> github.com/harbur/kubernetic-backend/pkg/apis.CreateStatefulSet (5 handlers)
[GIN-debug] POST   /api/namespaces/:namespace/statefulsets/:name/rollout/restart --> github.com/harbur/kubernetic-backend/pkg/apis.RestartStatefulSet (5 handlers)
[GIN-debug] GET    /api/kind/:kind           --> github.com/harbur/kubernetic-backend/pkg/apis.ListResources (5 handlers)
[GIN-debug] GET    /api/kind/:kind/:name     --> github.com/harbur/kubernetic-backend/pkg/apis.GetResource (5 handlers)
[GIN-debug] GET    /api/kind/:kind/:name/status --> github.com/harbur/kubernetic-backend/pkg/apis.GetResourceStatus (5 handlers)
[GIN-debug] GET    /api/kind/:kind/:name/backlink --> github.com/harbur/kubernetic-backend/pkg/apis.GetBacklink (5 handlers)
[GIN-debug] PUT    /api/kind/:kind/:name     --> github.com/harbur/kubernetic-backend/pkg/apis.UpdateResource (5 handlers)
[GIN-debug] POST   /api/kind                 --> github.com/harbur/kubernetic-backend/pkg/apis.CreateResource (5 handlers)
[GIN-debug] DELETE /api/kind/:kind/:name     --> github.com/harbur/kubernetic-backend/pkg/apis.DeleteResource (5 handlers)
[GIN-debug] PUT    /api/namespaces/:namespace/kind/:kind/:name/scaledown --> github.com/harbur/kubernetic-backend/pkg/apis.ScaleDown (5 handlers)
[GIN-debug] PUT    /api/namespaces/:namespace/kind/:kind/:name/scaleup --> github.com/harbur/kubernetic-backend/pkg/apis.ScaleUp (5 handlers)
[GIN-debug] POST   /api/namespaces           --> github.com/harbur/kubernetic-backend/pkg/apis.CreateNamespace (5 handlers)
[GIN-debug] PUT    /api/nodes/:name/cordon   --> github.com/harbur/kubernetic-backend/pkg/apis.CordonNode (5 handlers)
[GIN-debug] PUT    /api/nodes/:name/uncordon --> github.com/harbur/kubernetic-backend/pkg/apis.UncordonNode (5 handlers)
[GIN-debug] POST   /api/persistentvolumes    --> github.com/harbur/kubernetic-backend/pkg/apis.CreatePersistentVolume (5 handlers)
[GIN-debug] GET    /api/repositories         --> github.com/harbur/kubernetic-backend/pkg/apis.ListRepositories (5 handlers)
[GIN-debug] POST   /api/repositories         --> github.com/harbur/kubernetic-backend/pkg/apis.CreateRepository (5 handlers)
[GIN-debug] DELETE /api/repositories/:name   --> github.com/harbur/kubernetic-backend/pkg/apis.DeleteRepository (5 handlers)
[GIN-debug] GET    /api/license              --> github.com/harbur/kubernetic-backend/pkg/apis.ReadLicense (4 handlers)
[GIN-debug] PUT    /api/license              --> github.com/harbur/kubernetic-backend/pkg/apis.UpdateLicense (4 handlers)
[GIN-debug] POST   /api/license/activate     --> github.com/harbur/kubernetic-backend/pkg/apis.ActivateLicense (4 handlers)
[GIN-debug] POST   /api/license/trial        --> github.com/harbur/kubernetic-backend/pkg/apis.ActivateTrial (4 handlers)
[GIN-debug] POST   /api/license/validate     --> github.com/harbur/kubernetic-backend/pkg/apis.ValidateLicense (4 handlers)
[GIN-debug] GET    /api/preferences          --> github.com/harbur/kubernetic-backend/pkg/apis.ReadPreferences (4 handlers)
[GIN-debug] PUT    /api/preferences          --> github.com/harbur/kubernetic-backend/pkg/apis.UpdatePreferences (5 handlers)
[GIN-debug] POST   /api/browser              --> github.com/harbur/kubernetic-backend/pkg/apis.OpenLink (5 handlers)
[GIN-debug] POST   /api/namespaces/:namespace/cronjobs --> github.com/harbur/kubernetic-backend/pkg/apis.CreateCronJob (5 handlers)
[GIN-debug] GET    /api/portforward          --> github.com/harbur/kubernetic-backend/pkg/apis.ReadPortforwards (5 handlers)
[GIN-debug] POST   /api/portforward/:namespace/pods/:name/:port --> github.com/harbur/kubernetic-backend/pkg/apis.StartPortforward (5 handlers)
[GIN-debug] DELETE /api/portforward/:namespace/:resource/:name/:port --> github.com/harbur/kubernetic-backend/pkg/apis.StopPortforward (5 handlers)
[GIN-debug] POST   /api/portforward/:namespace/deployments/:name/:port --> github.com/harbur/kubernetic-backend/pkg/apis.StartPortforwardDeployment (5 handlers)
[GIN-debug] POST   /api/portforward/:namespace/statefulsets/:name/:port --> github.com/harbur/kubernetic-backend/pkg/apis.StartPortforwardStatefulSet (5 handlers)
[GIN-debug] POST   /api/portforward/:namespace/daemonsets/:name/:port --> github.com/harbur/kubernetic-backend/pkg/apis.StartPortforwardDaemonSet (5 handlers)
[GIN-debug] POST   /api/portforward/:namespace/jobs/:name/:port --> github.com/harbur/kubernetic-backend/pkg/apis.StartPortforwardJob (5 handlers)
[GIN-debug] POST   /api/portforward/:namespace/services/:name/:port --> github.com/harbur/kubernetic-backend/pkg/apis.StartPortforwardService (5 handlers)
[GIN-debug] GET    /api/portforward/:namespace/:resource/:name --> github.com/harbur/kubernetic-backend/pkg/apis.ReadPortforward (5 handlers)
[GIN-debug] GET    /api/filteredportforward/:resource --> github.com/harbur/kubernetic-backend/pkg/apis.ReadFilteredPortforwards (5 handlers)
[GIN-debug] GET    /ws/namespaces/:namespace/pods/:name/exec --> github.com/harbur/kubernetic-backend/pkg/apis.ExecPod (4 handlers)
[GIN-debug] GET    /ws/namespaces/:namespace/cronjobs/:name/logs --> github.com/harbur/kubernetic-backend/pkg/apis.WatchCronJobLogs (4 handlers)
[GIN-debug] GET    /ws/namespaces/:namespace/daemonsets/:name/logs --> github.com/harbur/kubernetic-backend/pkg/apis.WatchDaemonSetLogs (4 handlers)
[GIN-debug] GET    /ws/namespaces/:namespace/deployments/:name/logs --> github.com/harbur/kubernetic-backend/pkg/apis.WatchDeploymentLogs (4 handlers)
[GIN-debug] GET    /ws/namespaces/:namespace/jobs/:name/logs --> github.com/harbur/kubernetic-backend/pkg/apis.WatchJobLogs (4 handlers)
[GIN-debug] GET    /ws/namespaces/:namespace/pods/:name/logs --> github.com/harbur/kubernetic-backend/pkg/apis.WatchPodLogs (4 handlers)
[GIN-debug] GET    /ws/namespaces/:namespace/replicasets/:name/logs --> github.com/harbur/kubernetic-backend/pkg/apis.WatchReplicaSetLogs (4 handlers)
[GIN-debug] GET    /ws/namespaces/:namespace/replicationcontrollers/:name/logs --> github.com/harbur/kubernetic-backend/pkg/apis.WatchReplicationControllerLogs (4 handlers)
[GIN-debug] GET    /ws/namespaces/:namespace/statefulsets/:name/logs --> github.com/harbur/kubernetic-backend/pkg/apis.WatchStatefulSetLogs (4 handlers)
[GIN-debug] GET    /ws/namespaces/:namespace/taskruns/:name/logs --> github.com/harbur/kubernetic-backend/pkg/apis.WatchTaskRunsLogs (4 handlers)
[GIN-debug] GET    /ws/namespaces/:namespace/pipelineruns/:name/logs --> github.com/harbur/kubernetic-backend/pkg/apis.WatchPipelineRunsLogs (4 handlers)
[GIN-debug] GET    /ws/namespaces/:namespace/watch --> github.com/harbur/kubernetic-backend/pkg/apis.WatchNamespace (4 handlers)
[GIN-debug] GET    /ws/kind/:kind/watch      --> github.com/harbur/kubernetic-backend/pkg/apis.WatchResources (4 handlers)
[GIN-debug] GET    /ws/kind/:kind/resourceName/:name/watch --> github.com/harbur/kubernetic-backend/pkg/apis.WatchResource (4 handlers)
[GIN-debug] GET    /ws/kind/:kind/watchStatus --> github.com/harbur/kubernetic-backend/pkg/apis.WatchResourceStatus (4 handlers)
[GIN-debug] GET    /ws/watch                 --> github.com/harbur/kubernetic-backend/pkg/apis.WatchAllNamespaces (4 handlers)
[GIN-debug] GET    /ws/kind/:kind/name/:name/watchStatus --> github.com/harbur/kubernetic-backend/pkg/apis.WatchResourceStatusName (4 handlers)
[GIN-debug] POST   /api/namespaces/:namespace/roles --> github.com/harbur/kubernetic-backend/pkg/apis.CreateRole (5 handlers)
[GIN-debug] GET    /api/namespaces/:namespace/roles --> github.com/harbur/kubernetic-backend/pkg/apis.ListRoles (5 handlers)
[GIN-debug] GET    /api/discovery/groups     --> github.com/harbur/kubernetic-backend/pkg/apis.GetServerGroups (5 handlers)
[GIN-debug] GET    /api/discovery/resources  --> github.com/harbur/kubernetic-backend/pkg/apis.GetServerResources (5 handlers)
[GIN-debug] POST   /api/clusterroles         --> github.com/harbur/kubernetic-backend/pkg/apis.CreateClusterRole (5 handlers)
[GIN-debug] GET    /api/clusterroles         --> github.com/harbur/kubernetic-backend/pkg/apis.ListClusterRoles (5 handlers)
[GIN-debug] POST   /api/clusterrolebindings  --> github.com/harbur/kubernetic-backend/pkg/apis.CreateClusterRoleBinding (5 handlers)
[GIN-debug] POST   /api/namespaces/:namespace/rolebindings --> github.com/harbur/kubernetic-backend/pkg/apis.CreateRoleBinding (5 handlers)
[GIN-debug] GET    /api/namespaces/:namespace/deployments/:name/revisions --> github.com/harbur/kubernetic-backend/pkg/apis.GetRevisions (5 handlers)
[GIN-debug] POST   /api/namespaces/:namespace/deployments/:name/undo --> github.com/harbur/kubernetic-backend/pkg/apis.UndoDeployment (5 handlers)
[GIN-debug] GET    /api/customresourcedefinitions --> github.com/harbur/kubernetic-backend/pkg/apis.GetCustomResourceDefinitions (5 handlers)
[GIN-debug] GET    /api/apiresources         --> github.com/harbur/kubernetic-backend/pkg/apis.GetAPIResources (5 handlers)
[GIN-debug] GET    /api/customresources/:group/:version/:resource --> github.com/harbur/kubernetic-backend/pkg/apis.ListCustomResources (5 handlers)
[GIN-debug] GET    /api/customresources/:group/:version/:resource/:name --> github.com/harbur/kubernetic-backend/pkg/apis.GetCustomResource (5 handlers)
[GIN-debug] PUT    /api/customresources/:group/:version/:resource/:name --> github.com/harbur/kubernetic-backend/pkg/apis.UpdateCustomResource (5 handlers)
[GIN-debug] DELETE /api/customresources/:group/:version/:resource/:name --> github.com/harbur/kubernetic-backend/pkg/apis.DeleteCustomResource (5 handlers)
[GIN-debug] GET    /api/metrics/nodes/:name  --> github.com/harbur/kubernetic-backend/pkg/apis.GetMetricsNode (5 handlers)
[GIN-debug] GET    /api/metrics/nodes        --> github.com/harbur/kubernetic-backend/pkg/apis.GetMetricsNodes (5 handlers)
[GIN-debug] GET    /api/usage-metrics/pods   --> github.com/harbur/kubernetic-backend/pkg/apis.GetListUsageMetricsPods (5 handlers)
[GIN-debug] GET    /api/usage-metrics/pods/:name --> github.com/harbur/kubernetic-backend/pkg/apis.GetUsageMetricsPods (5 handlers)
[GIN-debug] GET    /api/usage-metrics/nodes  --> github.com/harbur/kubernetic-backend/pkg/apis.GetListUsageMetricsNodes (5 handlers)
[GIN-debug] GET    /api/usage-metrics/nodes/:name --> github.com/harbur/kubernetic-backend/pkg/apis.GetUsageMetricsNodes (5 handlers)
[GIN-debug] GET    /api/usage-metrics/deployments --> github.com/harbur/kubernetic-backend/pkg/apis.GetListUsageMetricsDeployments (5 handlers)
[GIN-debug] GET    /api/usage-metrics/deployments/:name --> github.com/harbur/kubernetic-backend/pkg/apis.GetUsageMetricsDeployments (5 handlers)
[GIN-debug] GET    /api/usage-metrics/statefulsets --> github.com/harbur/kubernetic-backend/pkg/apis.GetListUsageMetricsStateFulSet (5 handlers)
[GIN-debug] GET    /api/usage-metrics/statefulsets/:name --> github.com/harbur/kubernetic-backend/pkg/apis.GetUsageMetricsStateFulSet (5 handlers)
[GIN-debug] GET    /api/usage-metrics/daemonsets --> github.com/harbur/kubernetic-backend/pkg/apis.GetListUsageMetricsDaemonSets (5 handlers)
[GIN-debug] GET    /api/usage-metrics/daemonsets/:name --> github.com/harbur/kubernetic-backend/pkg/apis.GetUsageMetricsDaemonSets (5 handlers)
[GIN-debug] GET    /api/usage-metrics/jobs   --> github.com/harbur/kubernetic-backend/pkg/apis.GetListUsageMetricsJobs (5 handlers)
[GIN-debug] GET    /api/usage-metrics/jobs/:name --> github.com/harbur/kubernetic-backend/pkg/apis.GetUsageMetricsJobs (5 handlers)
[GIN-debug] GET    /api/timeseries-metrics/pods --> github.com/harbur/kubernetic-backend/pkg/apis.ListTimeseriesMetrics (5 handlers)
[GIN-debug] GET    /api/timeseries-metrics/deployments --> github.com/harbur/kubernetic-backend/pkg/apis.ListTimeseriesMetricsDeployment (5 handlers)
[GIN-debug] GET    /api/timeseries-metrics/statefulsets --> github.com/harbur/kubernetic-backend/pkg/apis.ListTimeseriesMetricsStatefulSets (5 handlers)
[GIN-debug] GET    /api/timeseries-metrics/daemonsets --> github.com/harbur/kubernetic-backend/pkg/apis.ListTimeseriesMetricsDaemonSets (5 handlers)
[GIN-debug] GET    /api/timeseries-metrics/jobs --> github.com/harbur/kubernetic-backend/pkg/apis.ListTimeseriesMetricsJobs (5 handlers)
[GIN-debug] GET    /api/timeseries-metrics/nodes --> github.com/harbur/kubernetic-backend/pkg/apis.ListTimeseriesMetricsNodes (5 handlers)
[GIN-debug] GET    /api/addons/metrics-server --> github.com/harbur/kubernetic-backend/pkg/apis.GetMetricsServer (5 handlers)
[GIN-debug] POST   /api/addons/metrics-server --> github.com/harbur/kubernetic-backend/pkg/apis.CreateMetricsServer (5 handlers)
[GIN-debug] PUT    /api/addons/metrics-server --> github.com/harbur/kubernetic-backend/pkg/apis.UpdateMetricsServer (5 handlers)
[GIN-debug] DELETE /api/addons/metrics-server --> github.com/harbur/kubernetic-backend/pkg/apis.DeleteMetricsServer (5 handlers)
[GIN-debug] GET    /api/addons/metrics-scraper --> github.com/harbur/kubernetic-backend/pkg/apis.GetMetricsScraper (5 handlers)
[GIN-debug] POST   /api/addons/metrics-scraper --> github.com/harbur/kubernetic-backend/pkg/apis.CreateMetricsScraper (5 handlers)
[GIN-debug] DELETE /api/addons/metrics-scraper --> github.com/harbur/kubernetic-backend/pkg/apis.DeleteMetricsScraper (5 handlers)
[GIN-debug] GET    /api/addons/operators     --> github.com/harbur/kubernetic-backend/pkg/apis.GetOperators (5 handlers)
[GIN-debug] POST   /api/addons/operators     --> github.com/harbur/kubernetic-backend/pkg/apis.CreateOperators (5 handlers)
[GIN-debug] DELETE /api/addons/operators     --> github.com/harbur/kubernetic-backend/pkg/apis.DeleteOperators (5 handlers)
[GIN-debug] GET    /api/operators            --> github.com/harbur/kubernetic-backend/pkg/apis.ListOperators (5 handlers)
[GIN-debug] GET    /api/operators/:name      --> github.com/harbur/kubernetic-backend/pkg/apis.GetOperator (5 handlers)
[GIN-debug] GET    /api/operators/:name/status --> github.com/harbur/kubernetic-backend/pkg/apis.GetOperatorStatus (5 handlers)
[GIN-debug] POST   /api/operators/:name      --> github.com/harbur/kubernetic-backend/pkg/apis.InstallOperator (5 handlers)
[GIN-debug] POST   /api/operatorsOptions/:name --> github.com/harbur/kubernetic-backend/pkg/apis.InstallOperatorOptions (5 handlers)
[GIN-debug] DELETE /api/operators/:name      --> github.com/harbur/kubernetic-backend/pkg/apis.DeleteInstallOperators (5 handlers)
[GIN-debug] DELETE /api/operatorsOptions/namespace/:namespace/:name --> github.com/harbur/kubernetic-backend/pkg/apis.DeleteInstallOperatorsOptions (5 handlers)
[GIN-debug] GET    /api/subscriptions        --> github.com/harbur/kubernetic-backend/pkg/apis.ListSubscriptions (5 handlers)
[GIN-debug] GET    /api/addons               --> github.com/harbur/kubernetic-backend/pkg/apis.ListAddons (5 handlers)
[GIN-debug] POST   /api/argo/argocds         --> github.com/harbur/kubernetic-backend/pkg/apis.CreateBasicApplications (6 handlers)
[GIN-debug] POST   /api/namespaces/:namespace/applications --> github.com/harbur/kubernetic-backend/pkg/apis.CreateApplications (6 handlers)
[GIN-debug] POST   /api/users                --> github.com/harbur/kubernetic-backend/pkg/apis.CreateUser (5 handlers)
[GIN-debug] PUT    /api/users/:name          --> github.com/harbur/kubernetic-backend/pkg/apis.UpdateUser (5 handlers)
[GIN-debug] DELETE /api/users/:name          --> github.com/harbur/kubernetic-backend/pkg/apis.DeleteUser (5 handlers)
[GIN-debug] GET    /api/users/:name          --> github.com/harbur/kubernetic-backend/pkg/apis.GetUser (5 handlers)
[GIN-debug] GET    /api/users                --> github.com/harbur/kubernetic-backend/pkg/apis.ListUsers (5 handlers)
[GIN-debug] GET    /api/enabledusers/:name   --> github.com/harbur/kubernetic-backend/pkg/apis.GetUserEnabled (5 handlers)
[GIN-debug] GET    /api/events/:uid          --> github.com/harbur/kubernetic-backend/pkg/apis.ListEvents (5 handlers)
[GIN-debug] GET    /api/whoami               --> github.com/harbur/kubernetic-backend/pkg/apis.GetWhoami (5 handlers)
[GIN-debug] POST   /api/tekton/tasks/:name/start --> github.com/harbur/kubernetic-backend/pkg/apis.StartTask (6 handlers)
[GIN-debug] POST   /api/tekton/clustertasks/:name/start --> github.com/harbur/kubernetic-backend/pkg/apis.StartClusterTask (6 handlers)
[GIN-debug] POST   /api/tekton/pipelines/:name/start --> github.com/harbur/kubernetic-backend/pkg/apis.StartPipeline (6 handlers)
[GIN-debug] DELETE /api/tekton/taskruns/:name/cancel --> github.com/harbur/kubernetic-backend/pkg/apis.CancelTaskRun (6 handlers)
[GIN-debug] DELETE /api/tekton/pipelineruns/:name/cancel --> github.com/harbur/kubernetic-backend/pkg/apis.CancelPipelineRun (6 handlers)
[GIN-debug] POST   /api/kind/pipelineresources --> github.com/harbur/kubernetic-backend/pkg/apis.CreatePipelineResource (6 handlers)
[GIN-debug] POST   /api/namespaces/:namespace/pods/:name/ephemeralcontainers --> github.com/harbur/kubernetic-backend/pkg/apis.CreateEphemeral (5 handlers)
[GIN-debug] Listening and serving HTTP on localhost:45424
time="2020-10-19T13:44:03+02:00" level=warning msg="Cannot configure logging level, falling back to Info" log.level=
time="2020-10-19T13:44:03+02:00" level=info msg="[GET] /api/license 200 (1ms)" latency=1 method=GET params= path=/api/license statusCode=200
time="2020-10-19T13:44:03+02:00" level=error msg="cannot open preferences"
time="2020-10-19T13:44:03+02:00" level=info msg="[GET] /api/preferences 200 (1ms)" latency=1 method=GET params= path=/api/preferences statusCode=200
time="2020-10-19T13:44:03+02:00" level=info msg="[GET] /api/license 200 (1ms)" latency=1 method=GET params= path=/api/license statusCode=200
time="2020-10-19T13:44:03+02:00" level=info msg="[POST] /api/license/validate 200 (1ms)" latency=1 method=POST params= path=/api/license/validate statusCode=200
```

**Comment by dkapanidis** [comment]
Thanks for the feedback, it seems to be linux-specific, we'll check it out to fix it for next version.

**Comment by AntonBlomstrom** [comment]
Thank you. It is indeed linux-specific, it worked fine when I used it on Windows 10. A quick fix would be to have a setting for disabling automatic update fetching so that the popup doesn't appear.

**Comment by jirkace** [comment]
any news for this? I'm using version 3.1.0 and the file `resources/app-update.yml` is stil missing

**Comment by AntonBlomstrom** [comment]
> any news for this? I'm using version 3.1.0 and the file `resources/app-update.yml` is stil missing

I'm not sure if they have fixed it. For the time being, I can recommend [https://k8slens.dev/](https://k8slens.dev/) as a replacement. 

Obviously, I would like there to be competition in the space. But so far, I have found Lens to work better on Ubuntu 20.10 at least.

**Comment by dkapanidis** [comment]
This is not fixed yet, I will notify here when the issue is resolved, in the meantime If you'd like to help with prioritisation of the issue you're more than welcome to invite others to upvote the issue with 👍 .

@AntonBlomstrom this is not a discussion board, please keep the conversation focused on the issue.

**Comment by boris779** [comment]
Still have this issue in Version 3.1.0

**Comment by jirkace** [comment]
@dkapanidis Please, is it possible to provide us the missing file? This startup error popup is annoying :-(

@boris779 Yes, I wrote about this version two months ago ^^

**Comment by stepanselyuk** [comment]
apt-update.yml
```
provider: s3
bucket: kubernetic
updaterCacheDirName: kubernetic-updater
```
But then I see an error about unauthorized access to S3.

**Comment by jirkace** [comment]
Thanks and yes, there is an Access Denied error

```
Error: HttpError: 403 Forbidden
"<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<Error><Code>AccessDenied</Code><Message>Access Denied</Message><RequestId>...............................</RequestId><HostId>..........................................</HostId></Error>"
Headers: {
  "x-amz-request-id": ".............................",
  "x-amz-id-2": ".............................................................................",
  "content-type": "application/xml",
  "transfer-encoding": "chunked",
  "date": "Sun, 16 May 2021 18:09:57 GMT",
  "server": "AmazonS3"
}
    at createHttpError (/home/blackie/kubernetic/resources/app.asar/node_modules/electron-updater/node_modules/builder-util-runtime/out/httpExecutor.js:84:10)
    at IncomingMessage.<anonymous> (/home/blackie/kubernetic/resources/app.asar/node_modules/electron-updater/node_modules/builder-util-runtime/out/httpExecutor.js:199:18)
    at IncomingMessage.emit (events.js:315:20)
    at endReadableNT (_stream_readable.js:1220:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
```

**Comment by stepanselyuk** [comment]
Probably better just to pack the application in Appimage format.
